name: Create release

on:
    push:
        branches:
            - master

jobs:
    check-commit:
        runs-on: ubuntu-latest
        outputs:
            result: ${{ steps.check.outputs.result }}
        steps:
            - uses: actions/checkout@v3
            - id: check
              run: |
                  result=$(echo "${{ github.event.head_commit.message }}" | grep -oP '^Update version to v\d+\.\d+\.\d+$')
                  echo "result=$result" >> $GITHUB_OUTPUT
    create-release:
        runs-on: ubuntu-latest
        needs: ["check-commit"]
        if: ${{ needs.check-commit.outputs.result != '' }}
        steps:
            - run: echo 'Hello there'
