name: Create tag and release

on:
    push:
        branches:
            - master

jobs:
    check-commit:
        runs-on: ubuntu-latest
        outputs:
            result: ${{ steps.check.outputs.result }}
        steps:
            - uses: actions/checkout@v3
            - id: check
              run: echo "result=$(echo '${{ github.event.head_commit.message }}' | grep -oP '^Update version to v\d+\.\d+\.\d+$')" >> $GITHUB_OUTPUT
              shell: bash
    create-release:
        runs-on: ubuntu-latest
        needs: ["check-commit"]
        if: ${{ needs.check-commit.outputs.result != '' }}
        steps:
            - uses: actions/checkout@v3
            - run: echo 'Hello there'
            - name: Get version
              id: get-version
              run: echo "version=$(echo '${{ needs.check-commit.outputs.result }}' | grep -oP 'v\d+\.\d+\.\d+')" >> $GITHUB_OUTPUT
              shell: bash
            - name: Generate body
              id: generate-body
              run: echo "body=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline)" >> "$GITHUB_OUTPUT"
            - uses: rickstaa/action-create-tag@v1
              with:
                  tag: "latest"
                  tag_exists_error: true
                  message: ${{ steps.get-version.outputs.version }}
            - uses: ncipollo/release-action@v1
              with:
                  name: ${{ steps.get-version.outputs.version }}
                  body: ${{ steps.generate-body.outputs.body }}
