name: Build test

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build-test:
        uses: marshall-ku/TEST/.github/workflows/build.yml@master
    cache-test:
        name: Cache test
        runs-on: ubuntu-latest
        needs: ["build-test"]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist/
            - run: cat dist/tmp.md
    send-notification:
        needs: [build-test, cache-test]
        if: ${{ failure() }}
        uses: marshall-ku/TEST/.github/workflows/reusable.yml@master
        with:
            status: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "test message"
        secrets:
            url: ${{ secrets.SLACK_WEBHOOK_URL }}