name: Publish package

on:
    release:
        types: [created]
    workflow_dispatch:
    repository_dispatch:

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: echo 'Hello world'
