name: Send slack notification

on:
  workflow_call:
    inputs:
      title:
        description: "Title of attachment"
        required: false
        default: "Failed to run job"
        type: string
      message:
        description: "Message to send"
        required: true
        type: string
      color:
        description: "Color of attachment"
        required: false
        default: "#808080"
        type: string
      author:
        description: "Author of attachment"
        required: false
        default: "Github Actions"
        type: string
    secrets:
      url:
        description: "Slack webhook url"
        required: true

jobs:
  run:
    name: Send notification
    runs-on: ubuntu-latest
    steps:
      - name: Make curl request
        run: |
          json_payload=$(cat << EOF
          {
            "attachments": [
                {
                    "color": "${{ inputs.color }}",
                    "author_name": "${{ inputs.author }}",
                    "author_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                    "title": "${{ inputs.title }}",
                    "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                    "text": "${{ inputs.message }}",
                    "fields": [
                        {
                            "title": "필드",
                            "value": "value",
                            "short": false
                        }
                    ]
                }
            ]
          }
          EOF
          )
          curl -X POST -H "Content-Type:application/json" -d "$json_payload" ${{ secrets.url }}
