name: Send slack notification

on:
  workflow_call:
    inputs:
      message:
        description: "Message to send"
        required: true
        type: string
    secrets:
      url:
        description: "Slack webhook url"
        required: true

jobs:
  run:
    name: Send notification
    runs-on: ubuntu-latest
    steps:
      - name: Make curl request
        run: |
          json_payload=$(
            cat <<EOF
            {
              "attachments": [
                  {
                      "color": "#2eb886",
                      "author_name": "github",
                      "author_link": "https://github.com/marshallku",
                      "author_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                      "title": "Title of attachment",
                      "title_link": "https://api.slack.com/",
                      "text": "${{ inputs.message }}",
                      "fields": [
                          {
                              "title": "필드",
                              "value": "value",
                              "short": false
                          }
                      ]
                  }
              ]
            }
            EOF
          )
          curl -X POST -H "Content-Type:application/json" -d "$json_payload" ${{ secrets.url }}
