name: Send slack notification

on:
  workflow_call:
    inputs:
      message:
        description: "Message to send"
        required: true
        type: string
    secrets:
      url:
        description: "Slack webhook url"
        required: true

jobs:
  run:
    name: Send notification
    runs-on: ubuntu-latest
    steps:
      - name: Make curl request
        run: curl -X POST -H "Content-Type:application/json" -d "{\"text\":\"${{ inputs.message }}\"}" ${{ secrets.url }}
