name: Send discord notification

on:
    workflow_call:
        inputs:
            status:
                description: "Status of job"
                required: true
                type: boolean
            message:
                description: "Message to send"
                required: false
                type: string
                default: ""
        secrets:
            url:
                description: "Webhook url"
                required: true

jobs:
    run:
        name: Send notification
        runs-on: ubuntu-latest
        steps:
            - name: Make curl request
              run: |
                  status=$([ "${{ inputs.status }}" == 'true' ] && echo 'failed' || echo 'succeeded')
                  color=$([ "${{ inputs.status }}" == 'true' ] && echo '16007990' || echo '5763719')
                  json_payload=$(cat << EOF
                  {
                      "embeds": [
                            {
                                "type": "rich",
                                "title": "Workflow $status",
                                "description": "${{ inputs.message }}",
                                "color": "$color",
                                "fields": [
                                    {
                                    "name": "Ref",
                                    "value": "${{ github.ref }}"
                                    },
                                    {
                                    "name": "URL",
                                    "value": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                                    },
                                    {
                                    "name": "Event",
                                    "value": "${{ github.event_name }}"
                                    }
                                ],
                                "footer": {
                                    "text": "${{ github.actor }}"
                                }
                            }
                      ]
                  }
                  EOF
                  )
                  curl -H "Content-Type:application/json" -d "$json_payload" "https://discord.com/api/webhooks/1164573510593679370/N8HBPxXwanKWO8kfxef7K2533W60UQBpU-rlK_dYLIcXwdQa0t1-aB0GIp_plNyCSnQl"
