name: Send slack notification

on:
  workflow_call:
    inputs:
      status:
        description: "Status of job"
        required: true
        type: boolean
      message:
        description: "Message to send"
        required: true
        type: string
    secrets:
      url:
        description: "Slack webhook url"
        required: true

jobs:
  run:
    name: Send notification
    runs-on: ubuntu-latest
    steps:
      - name: Make curl request
        run: |
          status=$([ "${{ inputs.status }}" == 'true' ] && echo 'succeeded' || echo 'failed')
          color=$([ "${{ inputs.status }}" == 'true' ] && echo '#66bb6a' || echo '#f44336')
          json_payload=$(cat << EOF
          {
            "attachments": [
                {
                    "color": "$color",
                    "author_name": "${{ github.actor }}",
                    "author_icon": "https://github.com/${{ github.actor }}.png",
                    "title": "Workflow <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}> $status",
                    "text": "${{ inputs.message }}",
                    "fields": [
                        {
                            "title": "Ref",
                            "value": "${{ github.ref_name }}",
                            "short": true
                        },
                        {
                            "title": "Event",
                            "value": "${{ github.event_name }}",
                            "short": true
                        },
                        {
                            "title": "Message",
                            "value": "${{ inputs.message }}",
                            "short": false
                        }
                    ]
                }
            ]
          }
          EOF
          )
          curl -X POST -H "Content-Type:application/json" -d "$json_payload" ${{ secrets.url }}
