name: Build test

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: 'echo 1'
              run: echo '1'
            - name: 'echo 2'
              run: echo '2'
            - name: 'echo 3'
              run: echo '3'
            - name: 'echo 4'
              run: echo '4'
    test2:
        name: Test2
        runs-on: ubuntu-latest
        steps:
            - name: 'will success'
              run: echo '1'
            - name: 'will fail'
              run: cd tmp && cat test.md
    test3:
        name: Test3
        runs-on: ubuntu-latest
        steps:
            - name: 'will success'
              run: echo '1'
    send-notification:
        needs: [test, test2, test3]
        if: ${{ failure() }}
        uses: marshall-ku/TEST/.github/workflows/reusable.yml@master
        with:
            status: ${{ contains(join(needs.*.result, ','), 'failure') }}
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
    check-status:
        needs: [test, test2, test3]
        runs-on: ubuntu-latest
        if: ${{ failure() }}
        steps:
            - run: echo ${{ contains(join(needs.*.result, ',')) }}
            - run: echo ${{ needs }}
